### ISSUE TITLE
logo principal du site

### ISSUE THREAD

**Issue by Karramiel** [Karramiel/LPC#4]

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/17008050/15400548/2e605f8e-1dec-11e6-85fe-9d3ba162c07d.png)

**Comment by Karramiel** [comment]
il est au régime ? il est ou le ventre grassouillé ?

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/17008050/15421678/eaa4597e-1e74-11e6-8844-fcc086bf638c.png)

**Comment by Karramiel** [comment]
Merci de l'afficher en svg avec les lettres LPC comme logo :)

**Comment by ghost** [comment]
Nouveaux logo mis en place, actuellement la font "Lato" ne fonctionne pas dans le logo sur le site via une importation par CSS. Je l'ai remplacé temporairement par "Roboto".

Je ne sais pas si Google lit le svg via importation par CSS comme du code ou une image.
S'il le vois comme une image je vectoriserai les lettres, si c'est du code faudra résoudre le problème ou changer de police.

**Comment by ghost** [comment]
Ou alors le logo sera seulement l'image du pingouins et LPC fera parti de la balise h1, mais google ne lira plus "Les pingouins connectés" par "L P C"

Ou alors on met l'image en PNG-8

**Comment by ghost** [comment]
Refont du html et css

```
<a class="cd-logo" href="<?php echo get_page_link(2350); ?>" title="les-pingouins-connectes.fr">
         <img src="<?php echo get_stylesheet_directory_uri() ?>/images/site/logo.svg" alt="Logo Les pingouins Connectés">
         <span>L P C</span>
</a>
```

logo en svg car toujours moins lourd que png, walla

**Comment by erwan1335** [comment]
Le site https://realfavicongenerator.net permet de décliner ton icon pour toute les plateformes, Ios, Chrome android, Windows, il donne même le code html 5 :)

Alors on pars sur ça où on reste juste sur un .ico 64x64 "pa bo" ? =)

**Comment by Karramiel** [comment]
Je ferme pour le moment
