### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by Karramiel** [Karramiel/LPC#50]

**Comment by ghost** [comment]
J'ai refait entièrement les réseaux sociaux en remplaçant les fonts par des svg et en refaisant entièrement le cercle animé.

le problème du décalage est toujours présent en fonction des pages, néanmoins j'ai réussi à faire en sorte que les svg ne bouge pas. il reste plus à faire la même chose pour le cercle.

**Comment by ghost** [comment]
Problème des réseaux sociaux résolu !

j'ai réussi en jouant avec les margins et les positions à faire en sorte que les réseaux sociaux ne soit plus  normalement influencé par le javascript.

(ça m'a pris plus de 3h tout ça ^^)

ps : je passe au réseaux sociaux des articles font --> svg

**Comment by ghost** [comment]
réseaux sociaux des produits fait sur la même base html qui les réseaux sociaux du footer, les classes varie en fonction de l'id de la nav donc différence visuelle pour même html :)

**Comment by Karramiel** [comment]
Il faudrait intégrer les deux pingouins (droite : pingouin contact ; gauche: pingouin social)

**Comment by ghost** [comment]
Correction d'un bug qui pouvait survenir en supprimant le z-index:10 par z-index:1 du footer et suppression de 

```
/*--------  footer  ----------------- */    


footer{
    position: relative;
    z-index:10;     

    }
#footer{
    background-color: #ff006c !important;
    }

.copyright{
    color:#FFF}

```

Du Style_base.less
