### ISSUE TITLE
Subheader : Image du parallax

### ISSUE THREAD

**Issue by Karramiel** [Karramiel/LPC#56]
-Trouver au moins une image par Template
-Mettre l'image à la une des produite/article comme image parallax (ne pas faire pour le moment)

**Comment by Karramiel** [comment]
Veilles à avoir des images optimisé de minimum 1024px :)

**Comment by ghost** [comment]
Je les réalise moi-même sur une taille temporaire de 3840x1080 =)
avec un poid de 200-300 ko

**Comment by Karramiel** [comment]
Si le rendu est bon, c'est encore mieux le maison !

**Comment by ghost** [comment]
Je suis parti sur du flat, je te montre un exemple sous peu

**Comment by Karramiel** [comment]
pour le template-produit trouves une image par default, je trouverai un moyen pour y intégrer automatiquement "l'image à la une" du produit. et si inexistante, celle par default que tu auras faite.

**Comment by ghost** [comment]
Sur le drive, 11-5 - Autres, y a l'image du parallaxe pour "contact" vu que c'est flat c'est 100ko :)

**Comment by Karramiel** [comment]
il faut voir le rendu mais pas fan de texte dans les images parallax

**Comment by ghost** [comment]
J'ai enlevé le texte sauf le titre, j'ai fait pour 4 Templates (celle de la foire aux objets n'est pas terminé car j'ai pas accès aux images de catégories)
et c'est dans les 30-80 ko par image

**Comment by ghost** [comment]
J'ai fait les modifications dont nous avons parlé, j'attends l'accès au site po
ur pouvoir les tester et savoir la taille et le positionnement des éléments

**Comment by ghost** [comment]
Les 4 images sont parfaitement installés pour un poids de 10-15 ko par image
