### ISSUE TITLE
Homepage : Triangle à remplacer

### ISSUE THREAD

**Issue by Karramiel** [Karramiel/LPC#57]
Remplacer le triangle par une div fix pour les versions tablette et mobile.

**Comment by ghost** [comment]
mise en place d'un background en triangle. le triangle est malheureusement en png et pas svg car celui-ci interagit différemment des autres images en css.

**Comment by Karramiel** [comment]
:'(

**Comment by ghost** [comment]
Remplacement du triangle.png en triangle.svg, avec quelques modifications de la balise background.
