### ISSUE TITLE
Favoris : Régler les décalages d'affichage des coeurs

### ISSUE THREAD

**Issue by Karramiel** [Karramiel/LPC#67]

**Comment by ghost** [comment]
Le problème est identique à celui du Footer, il sera pas aussi simple à résoudre que le Footer, mais il est "Temporairement résolu", j'ai joué avec les templates pour changer une valeur mais le problème reste quand même présent.

ancien code :

```
.portfolio_cube .love_bouton {
    top: 20px;
    right: 25px;
    position: absolute;
}
```

nouveau code temporaire : 

```
.portfolio_cube .love_bouton {
    right: 25px;
    position: absolute;
}

.foire_aux_objets-homepage .sections_group .portfolio_cube .love_bouton {
    top: 20px;
}
```

On as trois choix, soit refaire les cubes pour qu'il n'y a plus de position absolute et relative (c'est eux qui sont influencé par le problème), soit on joue avec les templates, soit on corrige le problème à sa source (recommandé).

**Comment by Karramiel** [comment]
Les mettres aligné par rapport au prix/logo caddie

**Comment by ghost** [comment]
Ajout de variables css pour le positionnement du love bouton pour la fiche produit et foire aux objets en liste

**Comment by ghost** [comment]
Ils sont déçà aligné au caddies, prix : 
![image](https://cloud.githubusercontent.com/assets/17008050/15115597/1ded9dc2-1600-11e6-946d-ef7a1b2ec370.png) (exemple en remontant verticalement le container_info)
