### ISSUE TITLE
Faire une vrai infographie

### ISSUE THREAD

**Issue by Karramiel** [Karramiel/LPC#68]
J'aimerai que tu regardes ce site dans un premier temps :

https://magic.piktochart.com/ 

1ere phase : 
Donc soit trouve de quoi t'inspiré sur ce site, soit sur un autre 
+
cherches des info sur les objet connecté, évolution des deux dernières année, % d'utilisation en france/monde, prix moyen... + les données déjà utilisé, (nb d'article , coms...). sur doc
(passes pas ton temps à la créer c'est pas le but)
fin de la phase 1 : présentation le soir

2eme phase : 
Tu mets au propre les données de la phase 1 avec l'infographie choisie
 fin de la phase 2 : validation le soir

3éme phase : 
coder l'info en dur sur LPC

**Comment by ghost** [comment]
Pour l'infographie, j'ai fait une toute petite partie sur le monde (estimation dans le monde en 2020, % d'utilisatation dans la monde) et une grande partie sur la France (qui en as utilisé,qui en achète? où les achète? ce qu'ils en pensent? 5top des IoT connu par les Français)

**Comment by Karramiel** [comment]
ok, je check ce soir

**Comment by ghost** [comment]
Infographie exporté en svg, mis dans le fichier "infographie.php" 
Modification du code pour avoir des mots au-lieu des lettres séparées. (30min)

Les modifications "visuelle" seront plus difficile à intégré sans demander de reconvertir les lettres

**Comment by ghost** [comment]
Importation de l'infographie.svg.
Modification de tous les textes pour qu'ils soient dans des balises <text> avec des <tspan> à l'intérieur pour le positionnement et/ou le changement de police.

(Ce qu'il reste à faire : inverser toutes les lignes de codes, ajouter les variables less pour les couleurs)
