### ISSUE TITLE
Color theme 

### ISSUE THREAD

**Issue by Karramiel** [Karramiel/LPC#70]
Primaire : 
#198881
# 31A697 (nuance)

Secondaire : 
# f96d5d

**Comment by ghost** [comment]
J'ai mis 10 propositions de coloris

[coloris.pdf](https://github.com/YannSeguillon/lpc/files/236649/coloris.pdf)

**Comment by Karramiel** [comment]
Haha le poisson d'avril c'était le 1er, a quand tes vrais propositions ? 
#jaidesgoutsdechiote

**Comment by ghost** [comment]
C'est le poisson du 26 Avril

J'aime bien la n°9

**Comment by ghost** [comment]
12 propositions centrées sur les couleurs des 2 choix
[coloris-2.pdf](https://github.com/YannSeguillon/lpc/files/238445/coloris-2.pdf)

**Comment by ghost** [comment]
![coloris-3](https://cloud.githubusercontent.com/assets/17008050/14885276/e34d62be-0d4a-11e6-8e92-2669b363770f.png)

**Comment by ghost** [comment]
Principal
#198881
#31A697

Secondaire
#F96D5D
