### ISSUE TITLE
Love bouton

### ISSUE THREAD

**Issue by ghost** [Karramiel/LPC#74]
Le texte des love bouton ne fonctionne pas pour la fiche produit.
Il fonctionne mal dans la foire aux objets en mode cadre (la couleur ne change pas au hover)

**Comment by erwan1335** [comment]
Ajout de variables css  pour le positionnement du love bouton pour la fiche produit et foire aux objets en liste

**Comment by Karramiel** [comment]
Good, perfect yann tu gères, tu rox du poney !

**Comment by ghost** [comment]
le modeste
