### ISSUE TITLE
Titre des pages

### ISSUE THREAD

**Issue by Karramiel** [Karramiel/LPC#78]
refonte des titres de page, cf doc psd

**Comment by ghost** [comment]
Refonte total du html et du css des titres

Intégration des titres au Subheader :+1: 

```
<div id="Subheader">

     <div class="container">
          <div class="parallax-container" id="foire">
               <div style="z-index:1;" class="parallax"><img src="<?php echo  get_stylesheet_directory_uri() ?>/images/site/subheader/subheader_foire-aux-objets.png"></div>
          </div>

     </div>

       <div class="subheader_text">
            <div class="cadre_titre valign-wrapper">
                 <h2 class="valign"><?php echo mfn_page_title() ?></h2>
            </div>

            <div class="chemin valign-wrapper" style="z-index:11">      
                 <!--  Breadcrumbs -->
                 <?php  echo mfn_breadcrumbs($breadcrumbs_link); ?>
            </div>          
     </div>
</div>
```

Mis en commentaire de certaines lignes de css de responsive.css et layout.css du thème principal par rapport au Subheader (fil d’Ariane).

Basé sur le modèle du .psd et entièrement responsive.

**Comment by ghost** [comment]
le h2 est maintenant en couleur secondaire

**Comment by Karramiel** [comment]
Verif ce soir et je ferme si tout est bon

**Comment by ghost** [comment]
Modification du width en min et max-width 

Modification du margin-bottom du cadre du titre pour le fil d'arianne

**Comment by Karramiel** [comment]
Très bien, bon résultat ! :) 
Je closed
