### ISSUE TITLE
Sous-menu

### ISSUE THREAD

**Issue by ghost** [Karramiel/LPC#82]
La mise en place de la barre de recherche à demandé de faire un "Overflow:visible" c'est a dire d'afficher les éléments hors de la div, hors le sous-menu n'est plus caché lorsqu'il n'est pas activé sur le homepage.

Peut être passer d'une hauteur de 0 à sa taille max, ça devrait faire le même effet sans débordement. A voir avec la version mobile.

**Comment by Karramiel** [comment]
@erwan1335 à mettre à jour :)
