### ISSUE TITLE
JS barre de recherche

### ISSUE THREAD

**Issue by ghost** [Karramiel/LPC#83]
Mettre en place un js pour désactiver la barre de recherche en mobile et desktop sous peine qui soit présent sur tablette et desktop-xl en plus des barres de recherche de base.

**Comment by Karramiel** [comment]
En css c'est pas possible avec media query et display none ?

**Comment by ghost** [comment]
le js passe place le css directement dans le html du coup il est toujours prioritaire que le css.

Mais je viens de résoudre le problème en forçant cela avec un `!important`: 

```
#active_search {    
    @media @desktop-xl, @tablet {
        display: none!important;
    }
}
```
