### ISSUE TITLE
Bug menu

### ISSUE THREAD

**Issue by Karramiel** [Karramiel/LPC#86]
le menu catégorie n'est pas visible en mode standard mais les buttons sont présent. désactiver ou trouver une solution

**Comment by ghost** [comment]
Rajout d'un display:none; aux li du menu_top lorsque celui-ci est caché.

```
ul {
    background-color: @primaire_light;
    height: 0px;
    padding: 0 50px 0 0;

     li {
        display: none;
        ...
    }
}

 .cd-main-nav.moves-out>li>ul>li {
    display: inline-block;
}
```

**Comment by ghost** [comment]
Modification du procédé :

Remplacement du "display:none;" par "visibility:hidden;" et du "display: inline-block;" par "visibility:visible"

cela permet de conserver l’animation de translation que le display:none bloquait sans changement pour l'utilisateur (les "li" sont toujours actifs mais non sélectionnable hors Developer Tools)

De plus la balise visibility est appliquée directement au lu "menu_top" pour contrer un bug
