### ISSUE TITLE
get_the_category_list()

### ISSUE THREAD

**Issue by ghost** [Karramiel/LPC#97]
Trouver comment enlever le "ul"  et "li" incrusté directement dans la fonction "get_the_category_list() "

**Comment by Karramiel** [comment]
title_li 

ça devrait t'aider.

**Comment by ghost** [comment]
Avant :
`<?php echo get_the_category_list() ?>`
Après :
`<?php echo get_the_category_list($args = array('title_li' => '0')) ?>`

**Comment by Karramiel** [comment]
Bien jeune padawan.

**Comment by ghost** [comment]
Modification par `<?php echo get_the_category_list($args = ', ') ?>`

pour mettre une virgule si y a plusieurs éléments
